"""remove foreign key from Stage

Revision ID: 0251e6b99560
Revises: f4dc7cdf2eec
Create Date: 2020-07-25 04:34:54.431268

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0251e6b99560'
down_revision = 'f4dc7cdf2eec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('stage_ibfk_1', 'stage', type_='foreignkey')
    op.drop_column('stage', 'route')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stage', sa.Column('route', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key('stage_ibfk_1', 'stage', 'route', ['route'], ['id'])
    # ### end Alembic commands ###
