"""DestinationDeparture model and schema 

Revision ID: 3df7ce5f10ff
Revises: 793fdfa6e14e
Create Date: 2020-07-25 04:47:52.008411

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3df7ce5f10ff'
down_revision = '793fdfa6e14e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('destination_departure',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_constraint('route_ibfk_2', 'route', type_='foreignkey')
    op.drop_constraint('route_ibfk_1', 'route', type_='foreignkey')
    op.create_foreign_key(None, 'route', 'destination_departure', ['destination'], ['id'])
    op.create_foreign_key(None, 'route', 'destination_departure', ['departure'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'route', type_='foreignkey')
    op.drop_constraint(None, 'route', type_='foreignkey')
    op.create_foreign_key('route_ibfk_1', 'route', 'stage', ['departure'], ['id'])
    op.create_foreign_key('route_ibfk_2', 'route', 'stage', ['destination'], ['id'])
    op.drop_table('destination_departure')
    # ### end Alembic commands ###
