"""added qr to db model

Revision ID: 46117c8b1b76
Revises: d754b3d322cd
Create Date: 2020-08-02 13:20:02.608055

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46117c8b1b76'
down_revision = 'd754b3d322cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mpesa', sa.Column('qr', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mpesa', 'qr')
    # ### end Alembic commands ###
