"""revert stage to orignal state

Revision ID: 793fdfa6e14e
Revises: 0251e6b99560
Create Date: 2020-07-25 04:41:32.913729

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '793fdfa6e14e'
down_revision = '0251e6b99560'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stage', sa.Column('route', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'stage', 'route', ['route'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'stage', type_='foreignkey')
    op.drop_column('stage', 'route')
    # ### end Alembic commands ###
