"""mpesa added 

Revision ID: 7da7a7f4d547
Revises: 77c7ce8c2d44
Create Date: 2020-07-08 09:49:25.865543

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7da7a7f4d547'
down_revision = '77c7ce8c2d44'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mpesa',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('receipt_number', sa.String(length=255), nullable=True),
    sa.Column('transaction_date', sa.String(length=255), nullable=True),
    sa.Column('phone_number', sa.Integer(), nullable=True),
    sa.Column('checkout_request_id', sa.String(length=255), nullable=True),
    sa.Column('merchant_request_id', sa.String(length=255), nullable=True),
    sa.Column('result_code', sa.Integer(), nullable=False),
    sa.Column('result_desc', sa.Text(), nullable=True),
    sa.Column('date_added', sa.DateTime(), nullable=True),
    sa.Column('local_transactional_key', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mpesa')
    # ### end Alembic commands ###
