"""payment schema modified

Revision ID: d754b3d322cd
Revises: 3748724bfdcc
Create Date: 2020-08-02 11:04:28.274079

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd754b3d322cd'
down_revision = '3748724bfdcc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mpesa', 'local_transactional_key')
    op.add_column('payment_dump', sa.Column('token', sa.String(length=255), nullable=False))
    op.add_column('payment_dump', sa.Column('user', sa.Integer(), nullable=False))
    op.alter_column('payment_dump', 'data',
               existing_type=mysql.TEXT(),
               nullable=True)
    op.create_foreign_key(None, 'payment_dump', 'user', ['user'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'payment_dump', type_='foreignkey')
    op.alter_column('payment_dump', 'data',
               existing_type=mysql.TEXT(),
               nullable=False)
    op.drop_column('payment_dump', 'user')
    op.drop_column('payment_dump', 'token')
    op.add_column('mpesa', sa.Column('local_transactional_key', mysql.VARCHAR(length=255), nullable=False))
    # ### end Alembic commands ###
