"""password token

Revision ID: f21ede423cc2
Revises: 3df7ce5f10ff
Create Date: 2020-07-31 02:11:47.288252

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f21ede423cc2'
down_revision = '3df7ce5f10ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('password_token_')
    op.drop_index('plate_number', table_name='vehicle')
    op.drop_table('vehicle')
    op.create_unique_constraint(None, 'car', ['plate_number'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'car', type_='unique')
    op.create_table('vehicle',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('plate_number', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('fleet_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('active', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('owner', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('in_service', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('route', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['fleet_id'], ['fleet.id'], name='vehicle_ibfk_1'),
    sa.ForeignKeyConstraint(['owner'], ['user.id'], name='vehicle_ibfk_2'),
    sa.ForeignKeyConstraint(['route'], ['route.id'], name='vehicle_ibfk_3'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_index('plate_number', 'vehicle', ['plate_number'], unique=True)
    op.create_table('password_token_',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('token', mysql.VARCHAR(length=250), nullable=False),
    sa.Column('active', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('date_added', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='password_token__ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
