"""stage and routes

Revision ID: f71fce1b0c02
Revises: 4da5362656be
Create Date: 2020-07-17 16:28:46.550994

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f71fce1b0c02'
down_revision = '4da5362656be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('car', sa.Column('route', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'car', 'route', ['route'], ['id'])
    op.add_column('stage', sa.Column('route', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'stage', 'route', ['route'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'stage', type_='foreignkey')
    op.drop_column('stage', 'route')
    op.drop_constraint(None, 'car', type_='foreignkey')
    op.drop_column('car', 'route')
    # ### end Alembic commands ###
