"""database user

Revision ID: f73c4fab2118
Revises: d68211c8f031
Create Date: 2020-07-16 05:19:32.438376

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f73c4fab2118'
down_revision = 'd68211c8f031'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('car', sa.Column('in_service', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('car', 'in_service')
    # ### end Alembic commands ###
